# Generated by Django 3.1.2 on 2020-11-01 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('cpf', models.CharField(max_length=11)),
                ('endereco', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=8)),
                ('ddd', models.IntegerField()),
                ('telefone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('codigo', models.IntegerField()),
                ('modelo', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='tipoItemProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDeItem', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='unidadeProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidadereferente', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precovendaVarejo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('precovendaAtacado', models.DecimalField(decimal_places=2, max_digits=6)),
                ('produtoReferentevenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtoReferentevenda', to='client.produto')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoEstoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantidadeProdutoReferente', models.IntegerField()),
                ('produtoReferente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtoReferente', to='client.produto')),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='tipoDeItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipodeitem', to='client.tipoitemproduto'),
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidade', to='client.unidadeproduto'),
        ),
    ]
