version: '3.8'

services:
  db:
    image: mariadb:10.5.8
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'my-app-db'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: 'password'
       MYSQL_ROOT_PASSWORD: 'password'
  web:
    build: .
    command: bash -c "cd /erp/ && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/erp
    ports:
      - "8000:8000"
    depends_on:
      - db