# Generated by Django 3.1.2 on 2020-11-02 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precovendaVarejo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('precovendaAtacado', models.DecimalField(decimal_places=2, max_digits=6)),
                ('produtoReferentevenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtoReferentevenda', to='produto.produto')),
            ],
        ),
    ]
