# Generated by Django 3.1.4 on 2020-12-12 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoriaProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('codigo', models.IntegerField()),
                ('modelo', models.CharField(max_length=25)),
                ('marca', models.CharField(max_length=25)),
                ('tags', models.CharField(blank=True, max_length=25)),
                ('codigoInterno', models.CharField(blank=True, max_length=25)),
                ('codigoBalanca', models.CharField(blank=True, max_length=25)),
                ('photo', models.ImageField(blank=True, upload_to='produtopy')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='produto.categoriaproduto')),
            ],
        ),
        migrations.CreateModel(
            name='tipoItemProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDeItem', models.CharField(max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='unidadeProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidadereferente', models.CharField(max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='subcategoriaProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=22)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='produto.categoriaproduto')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoEstoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movimentarEstoque', models.BooleanField()),
                ('movimentarEstoqueCompisicao', models.BooleanField()),
                ('custo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantidadeProdutoReferente', models.IntegerField()),
                ('produtoReferente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtoReferente', to='produto.produto')),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategoria', to='produto.subcategoriaproduto'),
        ),
        migrations.AddField(
            model_name='produto',
            name='tipoDeItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipodeitem', to='produto.tipoitemproduto'),
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidade', to='produto.unidadeproduto'),
        ),
    ]
