# Generated by Django 3.1.2 on 2020-11-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigoBalanca',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigoInterno',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='produto',
            name='photo',
            field=models.ImageField(blank=True, upload_to='produtopy'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tags',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
